;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="GameplayCue.MeleeHit.Axe.Sound",DevComment="")
+GameplayTagList=(Tag="GameplayCue.MeleeHit.Bat",DevComment="")
+GameplayTagList=(Tag="GameplayCue.MeleeHit.Block",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Sound.Death.FrostGiant",DevComment="// The Death Sound of Giant")
+GameplayTagList=(Tag="GameplayCue.Sound.Death.Glacier",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Sound.Death.Guardian",DevComment="")
+GameplayTagList=(Tag="GameplayCue.VFX.12",DevComment="")
+GameplayTagList=(Tag="GameplayCue.VFX.PerfectBlock",DevComment="")
+GameplayTagList=(Tag="GameplayCue.VFX.Shield",DevComment="")
+GameplayTagList=(Tag="GameplayCue.VFX.SuccesfulBlock",DevComment="")
+GameplayTagList=(Tag="Player.State.JumpToFinisher.Axe.Block",DevComment="")

